<a href="https://colab.research.google.com/github/souadoubah444/Assignment-1/blob/main/Assignment_1_DataWare_house_G_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install -q gcsfs

import pandas as pd
from google.colab import auth

In [2]:
auth.authenticate_user()

PROJECT_ID = "austin-bike-project-123456"
print("Using project:", PROJECT_ID)

Using project: austin-bike-project-123456

In [3]:
bucket_name = "austin-bike-project-123456"
file_path   = "Austin_MetroBike_Trips_20251204 (1).csv"

gcs_uri = f"gs://{bucket_name}/{file_path}"
print("Reading from:", gcs_uri)

df = pd.read_csv(gcs_uri)
df.head()

Reading from: gs://austin-bike-project-123456/Austin_MetroBike_Trips_20251204 (1).csv

/tmp/ipython-input-2280616129.py:7: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(gcs_uri)

,Trip ID,Membership or Pass Type,Bicycle ID,Bike Type,Checkout Datetime,Checkout Date,Checkout Time,Checkout Kiosk ID,Checkout Kiosk,Return Kiosk ID,Return Kiosk,Trip Duration Minutes,Month,Year
0,29710677,Local365,19847,electric,2023 May 24 06:32:11 PM,05/24/2023,18:32:11,2552.0,3rd/West,2552.0,4th/Guadalupe @ Republic Square,3,5,"2,023"
1,29745510,Local365,21491,electric,2023 May 28 02:12:12 PM,05/28/2023,14:12:12,3685.0,9th/Henderson,3685.0,2nd/Congress,6,5,"2,023"
2,29550686,Local365,157G,classic,2023 May 06 08:26:05 PM,05/06/2023,20:26:05,2497.0,11th/Congress @ The Texas Capitol,2497.0,21st/Guadalupe,10,5,"2,023"
3,29667683,Local365,17751,electric,2023 May 20 07:18:09 AM,05/20/2023,7:18:09,2504.0,South Congress/Elizabeth,2504.0,South Congress/Elizabeth,7,5,"2,023"
4,29632824,Local365,21455,electric,2023 May 15 05:12:36 PM,05/15/2023,17:12:36,2499.0,2nd/Lavaca @ City Hall,2499.0,South Congress/Elizabeth,8,5,"2,023"

In [4]:


df = df.rename(columns={
    "Trip ID": "trip_id",
    "Membership or Pass Type": "membership_type",
    "Bicycle ID": "bicycle_id",
    "Bike Type": "bike_type",
    "Checkout Datetime": "checkout_datetime",
    "Checkout Date": "checkout_date",
    "Checkout Time": "checkout_time",
    "Checkout Kiosk ID": "checkout_kiosk_id",
    "Checkout Kiosk": "checkout_kiosk",
    "Return Kiosk ID": "return_kiosk_id",
    "Return Kiosk": "return_kiosk",
    "Trip Duration Minutes": "duration_minutes",
    "Month": "month",
    "Year": "year"
})

df.head()

,trip_id,membership_type,bicycle_id,bike_type,checkout_datetime,checkout_date,checkout_time,checkout_kiosk_id,checkout_kiosk,return_kiosk_id,return_kiosk,duration_minutes,month,year
0,29710677,Local365,19847,electric,2023 May 24 06:32:11 PM,05/24/2023,18:32:11,2552.0,3rd/West,2552.0,4th/Guadalupe @ Republic Square,3,5,"2,023"
1,29745510,Local365,21491,electric,2023 May 28 02:12:12 PM,05/28/2023,14:12:12,3685.0,9th/Henderson,3685.0,2nd/Congress,6,5,"2,023"
2,29550686,Local365,157G,classic,2023 May 06 08:26:05 PM,05/06/2023,20:26:05,2497.0,11th/Congress @ The Texas Capitol,2497.0,21st/Guadalupe,10,5,"2,023"
3,29667683,Local365,17751,electric,2023 May 20 07:18:09 AM,05/20/2023,7:18:09,2504.0,South Congress/Elizabeth,2504.0,South Congress/Elizabeth,7,5,"2,023"
4,29632824,Local365,21455,electric,2023 May 15 05:12:36 PM,05/15/2023,17:12:36,2499.0,2nd/Lavaca @ City Hall,2499.0,South Congress/Elizabeth,8,5,"2,023"

In [5]:
!pip install -q gcsfs pandas-gbq google-cloud-bigquery

import pandas as pd
from google.colab import auth

In [6]:

auth.authenticate_user()

PROJECT_ID = "austin-bike-project-123456"
print("Using project:", PROJECT_ID)

Using project: austin-bike-project-123456

In [7]:
gcs_uri = "gs://austin-bike-project-123456/Austin_MetroBike_Trips_20251204 (1).csv"
print("Reading from:", gcs_uri)

df = pd.read_csv(gcs_uri)

df.head()

Reading from: gs://austin-bike-project-123456/Austin_MetroBike_Trips_20251204 (1).csv

/tmp/ipython-input-3758845217.py:4: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(gcs_uri)

,Trip ID,Membership or Pass Type,Bicycle ID,Bike Type,Checkout Datetime,Checkout Date,Checkout Time,Checkout Kiosk ID,Checkout Kiosk,Return Kiosk ID,Return Kiosk,Trip Duration Minutes,Month,Year
0,29710677,Local365,19847,electric,2023 May 24 06:32:11 PM,05/24/2023,18:32:11,2552.0,3rd/West,2552.0,4th/Guadalupe @ Republic Square,3,5,"2,023"
1,29745510,Local365,21491,electric,2023 May 28 02:12:12 PM,05/28/2023,14:12:12,3685.0,9th/Henderson,3685.0,2nd/Congress,6,5,"2,023"
2,29550686,Local365,157G,classic,2023 May 06 08:26:05 PM,05/06/2023,20:26:05,2497.0,11th/Congress @ The Texas Capitol,2497.0,21st/Guadalupe,10,5,"2,023"
3,29667683,Local365,17751,electric,2023 May 20 07:18:09 AM,05/20/2023,7:18:09,2504.0,South Congress/Elizabeth,2504.0,South Congress/Elizabeth,7,5,"2,023"
4,29632824,Local365,21455,electric,2023 May 15 05:12:36 PM,05/15/2023,17:12:36,2499.0,2nd/Lavaca @ City Hall,2499.0,South Congress/Elizabeth,8,5,"2,023"

In [8]:

print(df.columns.tolist())

df = df.rename(columns={
    "Trip ID": "trip_id",
    "Membership or Pass Type": "membership_type",
    "Bicycle ID": "bicycle_id",
    "Bike Type": "bike_type",
    "Checkout Datetime": "checkout_datetime",
    "Checkout Date": "checkout_date",
    "Checkout Time": "checkout_time",
    "Checkout Kiosk ID": "checkout_kiosk_id",
    "Checkout Kiosk": "checkout_kiosk",
    "Return Kiosk ID": "return_kiosk_id",
    "Return Kiosk": "return_kiosk",
    "Trip Duration Minutes": "trip_duration_minutes",
    "Month": "month_raw",
    "Year": "year_raw"
})

df.head()

['Trip ID', 'Membership or Pass Type', 'Bicycle ID', 'Bike Type', 'Checkout Datetime', 'Checkout Date', 'Checkout Time', 'Checkout Kiosk ID', 'Checkout Kiosk', 'Return Kiosk ID', 'Return Kiosk', 'Trip Duration Minutes', 'Month', 'Year']

,trip_id,membership_type,bicycle_id,bike_type,checkout_datetime,checkout_date,checkout_time,checkout_kiosk_id,checkout_kiosk,return_kiosk_id,return_kiosk,trip_duration_minutes,month_raw,year_raw
0,29710677,Local365,19847,electric,2023 May 24 06:32:11 PM,05/24/2023,18:32:11,2552.0,3rd/West,2552.0,4th/Guadalupe @ Republic Square,3,5,"2,023"
1,29745510,Local365,21491,electric,2023 May 28 02:12:12 PM,05/28/2023,14:12:12,3685.0,9th/Henderson,3685.0,2nd/Congress,6,5,"2,023"
2,29550686,Local365,157G,classic,2023 May 06 08:26:05 PM,05/06/2023,20:26:05,2497.0,11th/Congress @ The Texas Capitol,2497.0,21st/Guadalupe,10,5,"2,023"
3,29667683,Local365,17751,electric,2023 May 20 07:18:09 AM,05/20/2023,7:18:09,2504.0,South Congress/Elizabeth,2504.0,South Congress/Elizabeth,7,5,"2,023"
4,29632824,Local365,21455,electric,2023 May 15 05:12:36 PM,05/15/2023,17:12:36,2499.0,2nd/Lavaca @ City Hall,2499.0,South Congress/Elizabeth,8,5,"2,023"

In [9]:

df["checkout_datetime"] = pd.to_datetime(
    df["checkout_datetime"],
    errors="coerce",
    infer_datetime_format=True
)


df["trip_duration_minutes"] = pd.to_numeric(
    df["trip_duration_minutes"],
    errors="coerce"
)


df[["checkout_datetime", "trip_duration_minutes"]].head()

/tmp/ipython-input-3262765695.py:1: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  df["checkout_datetime"] = pd.to_datetime(
/tmp/ipython-input-3262765695.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["checkout_datetime"] = pd.to_datetime(

    checkout_datetime  trip_duration_minutes
0 2023-05-24 18:32:11                    3.0
1 2023-05-28 14:12:12                    6.0
2 2023-05-06 20:26:05                   10.0
3 2023-05-20 07:18:09                    7.0
4 2023-05-15 17:12:36                    8.0

In [10]:

df["checkout_datetime"] = pd.to_datetime(
    df["checkout_datetime"],
    errors="coerce",
    infer_datetime_format=True
)


df["trip_duration_minutes"] = pd.to_numeric(
    df["trip_duration_minutes"],
    errors="coerce"
)


df[["checkout_datetime", "trip_duration_minutes"]].head()

/tmp/ipython-input-3262765695.py:1: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  df["checkout_datetime"] = pd.to_datetime(

    checkout_datetime  trip_duration_minutes
0 2023-05-24 18:32:11                    3.0
1 2023-05-28 14:12:12                    6.0
2 2023-05-06 20:26:05                   10.0
3 2023-05-20 07:18:09                    7.0
4 2023-05-15 17:12:36                    8.0

In [11]:

df["return_datetime"] = df["checkout_datetime"] + pd.to_timedelta(
    df["trip_duration_minutes"], unit="m"
)


df["checkout_date"] = df["checkout_datetime"].dt.date
df["return_date"]   = df["return_datetime"].dt.date

df[["checkout_datetime", "checkout_date", "return_datetime", "return_date"]].head()

    checkout_datetime checkout_date     return_datetime return_date
0 2023-05-24 18:32:11    2023-05-24 2023-05-24 18:35:11  2023-05-24
1 2023-05-28 14:12:12    2023-05-28 2023-05-28 14:18:12  2023-05-28
2 2023-05-06 20:26:05    2023-05-06 2023-05-06 20:36:05  2023-05-06
3 2023-05-20 07:18:09    2023-05-20 2023-05-20 07:25:09  2023-05-20
4 2023-05-15 17:12:36    2023-05-15 2023-05-15 17:20:36  2023-05-15

In [12]:

df["year"]        = df["checkout_datetime"].dt.year
df["month"]       = df["checkout_datetime"].dt.month
df["day"]         = df["checkout_datetime"].dt.day
df["hour"]        = df["checkout_datetime"].dt.hour
df["day_of_week"] = df["checkout_datetime"].dt.day_name()
df["hour_of_day"] = df["checkout_datetime"].dt.hour

df["is_round_trip"] = (df["checkout_kiosk_id"] == df["return_kiosk_id"])

df[[
    "trip_id", "bicycle_id", "checkout_datetime", "return_datetime",
    "trip_duration_minutes", "day_of_week", "hour_of_day", "is_round_trip"
]].head()

,trip_id,bicycle_id,checkout_datetime,return_datetime,trip_duration_minutes,day_of_week,hour_of_day,is_round_trip
0,29710677,19847,2023-05-24 18:32:11,2023-05-24 18:35:11,3.0,Wednesday,18,True
1,29745510,21491,2023-05-28 14:12:12,2023-05-28 14:18:12,6.0,Sunday,14,True
2,29550686,157G,2023-05-06 20:26:05,2023-05-06 20:36:05,10.0,Saturday,20,True
3,29667683,17751,2023-05-20 07:18:09,2023-05-20 07:25:09,7.0,Saturday,7,True
4,29632824,21455,2023-05-15 17:12:36,2023-05-15 17:20:36,8.0,Monday,17,True

In [13]:

before = len(df)
df = df.drop_duplicates(subset=["trip_id"])
after = len(df)
print("Duplicates removed:", before - after)


for col in ["trip_id", "bicycle_id", "checkout_kiosk_id", "return_kiosk_id"]:
    df[col] = pd.to_numeric(df[col], errors="coerce").astype("Int64")


critical_cols = [
    "trip_id", "checkout_datetime", "return_datetime",
    "checkout_kiosk_id", "return_kiosk_id", "bicycle_id"
]
before = len(df)
df = df.dropna(subset=critical_cols)
after = len(df)
print("Rows removed due to NULLs:", before - after)
print("Final row count:", after)

Duplicates removed: 0
Rows removed due to NULLs: 111966
Final row count: 2159187

In [14]:

df["date_key"] = df["checkout_datetime"].dt.strftime("%Y%m%d").astype(int)

dim_date = pd.DataFrame({
    "date_key": df["date_key"],
    "date": df["checkout_date"],
    "year": df["year"],
    "month": df["month"],
    "day": df["day"],
    "hour": df["hour"]
}).drop_duplicates().reset_index(drop=True)

dim_date.head()

   date_key        date  year  month  day  hour
0  20230524  2023-05-24  2023      5   24    18
1  20230528  2023-05-28  2023      5   28    14
2  20230520  2023-05-20  2023      5   20     7
3  20230515  2023-05-15  2023      5   15    17
4  20230502  2023-05-02  2023      5    2    16

In [ ]:

stations_checkout = df[["checkout_kiosk_id", "checkout_kiosk"]].rename(
    columns={"checkout_kiosk_id": "station_id", "checkout_kiosk": "station_name"}
)
stations_return = df[["return_kiosk_id", "return_kiosk"]].rename(
    columns={"return_kiosk_id": "station_id", "return_kiosk": "station_name"}
)

dim_station = pd.concat([stations_checkout, stations_return], ignore_index=True)
dim_station = dim_station.dropna(subset=["station_id"]).drop_duplicates().reset_index(drop=True)


dim_station["station_id"] = dim_station["station_id"].astype("Int64")

dim_station.head()

In [ ]:
dim_bike = df[["bicycle_id", "bike_type"]].drop_duplicates().reset_index(drop=True)
dim_bike = dim_bike.rename(columns={"bicycle_id": "bike_id"})
dim_bike["bike_id"] = dim_bike["bike_id"].astype("Int64")

dim_bike.head()

In [ ]:
dim_membership = df[["membership_type"]].drop_duplicates().reset_index(drop=True)
dim_membership["membership_key"] = range(1, len(dim_membership) + 1)

dim_membership.head()

In [ ]:
fact = df.copy()

fact = fact.merge(dim_bike, left_on="bicycle_id", right_on="bike_id", how="left")


fact = fact.merge(dim_membership, on="membership_type", how="left")


fact = fact.rename(columns={
    "checkout_kiosk_id": "station_start_id",
    "return_kiosk_id":   "station_end_id"
})


fact["trip_key"] = range(1, len(fact) + 1)


fact_trips = fact[[
    "trip_key",
    "trip_id",
    "date_key",
    "station_start_id",
    "station_end_id",
    "bike_id",
    "membership_key",
    "checkout_datetime",
    "return_datetime",
    "trip_duration_minutes",
    "day_of_week",
    "hour_of_day",
    "is_round_trip"
]]

fact_trips.head()

In [ ]:
from google.colab import auth
auth.authenticate_user()
print("Authenticated!")

In [20]:
PROJECT_ID = "austin-bike-project-123456"
print("Using project:", PROJECT_ID)

Using project: austin-bike-project-123456

In [21]:
from google.colab import auth
auth.authenticate_user()


GCS_PROJECT_ID = "austin-bike-project-123456"


PROJECT_ID = "opportunte-eye-480302-k6"
DATASET_ID = "austin_bike_dw"

print("GCS project:", GCS_PROJECT_ID)
print("BigQuery project:", PROJECT_ID)

GCS project: austin-bike-project-123456
BigQuery project: opportunte-eye-480302-k6

In [22]:
from google.cloud import bigquery

PROJECT_ID = "opportunte-eye-480302-k6"
DATASET_ID = "austin_bike_dw"

client = bigquery.Client(project=PROJECT_ID)
print("BigQuery client ready for dataset:", f"{PROJECT_ID}.{DATASET_ID}")

BigQuery client ready for dataset: opportunte-eye-480302-k6.austin_bike_dw

In [23]:
import pandas_gbq

def load_to_bq(df_bq, table_name):
    full_table_id = f"{DATASET_ID}.{table_name}"
    print("Loading to:", full_table_id)

    pandas_gbq.to_gbq(
        df_bq,
        full_table_id,
        project_id=PROJECT_ID,
        if_exists="replace",
    )
    print("✅ Done.\n")

In [28]:
PROJECT_ID = "opportunte-eye-480302-k6"
DATASET_ID = "austin_bike_dw"

print("BigQuery project:", PROJECT_ID)
print("Dataset:", DATASET_ID)

BigQuery project: opportunte-eye-480302-k6
Dataset: austin_bike_dw

In [27]:
import pandas_gbq

def load_to_bq(df_bq, table_name):
    full_table_id = f"{DATASET_ID}.{table_name}"
    print("Loading to:", full_table_id)

    pandas_gbq.to_gbq(
        df_bq,
        full_table_id,
        project_id=PROJECT_ID,
        if_exists="replace",
    )

    print("✅ Done.\n")

In [29]:
!pip install -q pandas-gbq google-cloud-bigquery

In [30]:
from google.colab import auth
auth.authenticate_user()
print("Authenticated!")

Authenticated!

In [31]:
PROJECT_ID = "opportune-eye-480302-k6"   # <-- type EXACTLY as it appears in BigQuery
DATASET_ID = "austin_bike_dw"            # dataset you already see in BigQuery

print("BigQuery project:", PROJECT_ID)
print("Dataset:", DATASET_ID)

BigQuery project: opportune-eye-480302-k6
Dataset: austin_bike_dw

In [32]:
for name in ["dim_date", "dim_station", "dim_bike", "dim_membership", "fact_trips"]:
    print(name, "exists?", name in globals())

dim_date exists? True
dim_station exists? True
dim_bike exists? True
dim_membership exists? True
fact_trips exists? True

In [34]:
import pandas_gbq

def load_to_bq(df_bq, table_name):
    """
    Load a pandas DataFrame into BigQuery
    as DATASET_ID.table_name in PROJECT_ID.
    """
    full_table_id = f"{DATASET_ID}.{table_name}"
    print("Loading to:", full_table_id)

    pandas_gbq.to_gbq(
        df_bq,
        full_table_id,
        project_id=PROJECT_ID,
        if_exists="replace",   # overwrite if it already exists
    )

    print("✅ Done loading", full_table_id, "\n")

In [35]:
load_to_bq(dim_date,       "dim_date")
load_to_bq(dim_station,    "dim_station")
load_to_bq(dim_bike,       "dim_bike")
load_to_bq(dim_membership, "dim_membership")

Loading to: austin_bike_dw.dim_date

100%|██████████| 1/1 [00:00<00:00, 831.38it/s]

✅ Done loading austin_bike_dw.dim_date

Loading to: austin_bike_dw.dim_station

100%|██████████| 1/1 [00:00<00:00, 9845.78it/s]

✅ Done loading austin_bike_dw.dim_station

Loading to: austin_bike_dw.dim_bike

100%|██████████| 1/1 [00:00<00:00, 9776.93it/s]

✅ Done loading austin_bike_dw.dim_bike

Loading to: austin_bike_dw.dim_membership

100%|██████████| 1/1 [00:00<00:00, 11397.57it/s]

✅ Done loading austin_bike_dw.dim_membership

In [36]:
load_to_bq(fact_trips, "fact_trips")

Loading to: austin_bike_dw.fact_trips

100%|██████████| 1/1 [00:00<00:00, 10979.85it/s]

✅ Done loading austin_bike_dw.fact_trips